const zones={coastal:["Coastal Ward","HIGH",14200],harbour:["Harbour","HIGH",8600],oldtown:["Old Town","WATCH",11800],riverside:["Riverside","WATCH",9700],industrial:["Industrial","WATCH",7600],north:["North Hills","LOW",6200],market:["Market District","LOW",10400],villages:["Outer Villages","WATCH",13950]};
const state={hours:72,budget:100,safety:82,distance:720,confidence:61,wind:55,turn:1,ended:false};
const $=id=>document.getElementById(id),feed=$("feed");
function addFeed(m){const e=document.createElement("div");e.className="feed-item";e.textContent=m;feed.prepend(e);while(feed.children.length>5)feed.lastChild.remove()}
function render(){ $("clock").textContent=String(state.hours).padStart(2,"0")+":00";$("turn").textContent="TURN "+state.turn+" / 12";$("budget").textContent="₹"+state.budget;$("safety").textContent=Math.max(0,state.safety)+"%";$("distance").textContent=state.distance+" km";$("confidence").textContent=state.confidence+"%";$("wind").textContent="WIND "+state.wind+" km/h";$("phase").textContent=state.hours>48?"PREPARATION PHASE":state.hours>24?"ESCALATION PHASE":"CRISIS PHASE";const p=(720-state.distance)/720,s=$("storm");s.style.right=(3+p*45)+"%";s.style.bottom=(5+p*30)+"%";s.style.transform="scale("+(1+p*.8)+")";document.querySelectorAll(".action").forEach(b=>b.disabled=state.ended||state.budget<(b.dataset.action==="evacuate"?15:b.dataset.action==="shelter"?10:b.dataset.action==="warning"?5:b.dataset.action==="hospital"?12:8))}
function spend(c){if(state.budget<c)return false;state.budget-=c;return true}
function randomEvent(){const es=[["Hospital generator failure reported.",-2],["Heavy rainfall is flooding low-lying streets.",-3],["Bridge blockage detected on the Riverside route.",-2],["Mobile network congestion is slowing warnings.",-1],["Volunteers arrive with boats and food.",3],["Forecast models converge on a narrower corridor.",2]];const e=es[Math.floor(Math.random()*es.length)];state.safety+=e[1];addFeed("EVENT • "+e[0]);$("alert").textContent=e[0]}
function takeAction(action){if(state.ended)return;const c={evacuate:[15,8,"Evacuation convoy dispatched. Vulnerable families are moving inland."],shelter:[10,6,"Shelters stocked with food, water and backup power."],warning:[5,4,"Public warning issued. Compliance and trust improve."],hospital:[12,7,"Hospital readiness upgraded with generator and medicine."],roads:[8,5,"Critical roads secured and emergency vehicles repositioned."]}[action];if(!spend(c[0])){addFeed("COMMAND BLOCKED • Insufficient budget.");return}state.safety=Math.min(100,state.safety+c[1]);state.hours-=6;state.turn++;state.distance=Math.max(0,state.distance-95);state.wind=Math.min(145,state.wind+8);state.confidence=Math.min(95,state.confidence+Math.floor(Math.random()*8));addFeed("COMMAND • "+c[2]);$("decisionBox").innerHTML="<strong>DECISION LOGGED</strong><p>"+c[2]+" You have "+state.hours+" hours remaining.</p>";if(state.turn%2===0)randomEvent();state.safety=Math.max(0,state.safety-(state.hours<=24?3:1));render();if(state.hours<=0)endGame()}
function endGame(){state.ended=true;state.hours=0;render();const people=Math.round(86250*(state.safety/100)),grade=state.safety>=90?"A":state.safety>=80?"B":state.safety>=65?"C":"D";$("finalSafety").textContent=state.safety+"%";$("people").textContent=people.toLocaleString("en-IN");$("leftBudget").textContent="₹"+state.budget;$("grade").textContent=grade;$("reportText").textContent="Landfall has occurred. Your command protected an estimated "+people.toLocaleString("en-IN")+" people. The outcome reflects preparation, resource limits, uncertainty and cascading events.";$("report").hidden=false;$("report").scrollIntoView({behavior:"smooth"});addFeed("LANDFALL • Final city safety: "+state.safety+"%")}
document.querySelectorAll(".action").forEach(b=>b.addEventListener("click",()=>takeAction(b.dataset.action)));
document.querySelectorAll(".zone").forEach(z=>z.addEventListener("click",()=>{document.querySelectorAll(".zone").forEach(x=>x.classList.remove("selected"));z.classList.add("selected");const d=zones[z.dataset.zone];$("decisionBox").innerHTML="<strong>ZONE INTELLIGENCE</strong><p><b>"+d[0]+"</b> — "+d[1]+" RISK. Approx. "+d[2].toLocaleString("en-IN")+" residents. Choose an action based on your priorities.</p>";addFeed("MAP • "+d[0]+" selected.")}));
$("restart").addEventListener("click",()=>location.reload());
addFeed("SYSTEM • Cyclone warning received. 72 hours until projected landfall.");
addFeed("FORECAST • Three models show different landfall corridors.");
addFeed("COMMAND • You control budget, preparedness and response.");
render();