(function(){
if(window.__L72_TUTORIAL__)return;window.__L72_TUTORIAL__=true;
var missions=[
{t:"FIRST WARNING",z:"COASTAL WARD",d:"NORTH-WEST",a:"3",x:"Reach Coastal Ward and issue the first warning."},
{t:"EVACUATION RUN",z:"HARBOUR",d:"NORTH-EAST",a:"1",x:"Reach Harbour and evacuate vulnerable families."},
{t:"BRIDGE COLLAPSE",z:"RIVERSIDE",d:"SOUTH-WEST",a:"5",x:"Secure the emergency corridor."},
{t:"HOSPITAL CRISIS",z:"OLD TOWN",d:"EAST",a:"4",x:"Reinforce hospital readiness."},
{t:"SHELTER OVERLOAD",z:"OUTER VILLAGES",d:"SOUTH",a:"2",x:"Expand emergency shelter capacity."}];
var s=document.createElement("style");s.textContent='.l72-t{position:fixed;inset:0;z-index:9999;background:#01060acc;display:flex;align-items:center;justify-content:center;font-family:Arial}.l72-t.h{display:none}.l72-c{width:min(680px,92vw);background:#071722;border:1px solid #67f5d055;border-radius:16px;padding:26px;color:#eafff8;box-shadow:0 25px 90px #000}.l72-c h2{font-size:30px;margin:7px 0}.l72-c p{color:#9db4bc;font-size:12px;line-height:1.5}.l72-keys{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.l72-keys div{padding:11px;background:#08141e;border:1px solid #294653;border-radius:8px}.l72-keys b{display:block;color:#9fffe5;font-size:14px}.l72-keys span{font-size:9px;color:#829da7}.l72-go{width:100%;padding:13px;border:0;border-radius:8px;background:#67f5d0;font-weight:900}.l72-tr{position:fixed;left:18px;top:78px;width:285px;z-index:5000;background:#030b11e8;border:1px solid #9fffe533;border-left:3px solid #67f5d0;border-radius:9px;padding:12px;color:#eafff8;font:10px Arial}.l72-tr small{color:#78939e}.l72-tr h3{margin:4px 0;font-size:16px}.l72-tr p{color:#a9bdc3}.l72-w{color:#ffc857!important;font-weight:bold}.l72-nav{position:fixed;right:18px;top:78px;z-index:5000;width:190px;background:#030b11e0;border:1px solid #ffffff18;border-radius:9px;padding:10px;color:#eafff8;font:9px Arial}.l72-nav .ar{font-size:30px;text-align:center;color:#67f5d0}.l72-nav strong,.l72-nav span{display:block;text-align:center}.l72-nav span{color:#78939e;font-size:7px}.l72-list div{padding:5px;border-top:1px solid #ffffff0d;color:#617c87}.l72-list .on{color:#9fffe5;background:#0a211f}.l72-tip{position:fixed;left:50%;bottom:62px;transform:translateX(-50%);z-index:5000;background:#030b11e8;border:1px solid #67f5d055;border-radius:7px;padding:8px 12px;color:#cfe3e5;font:9px Arial}@media(max-width:760px){.l72-tr{left:8px;right:8px;top:58px;width:auto}.l72-nav{right:8px;bottom:125px;top:auto}.l72-keys{grid-template-columns:1fr 1fr}}';document.head.appendChild(s);
var t=document.createElement("div");t.className="l72-t";t.innerHTML='<div class="l72-c"><small style="color:#67f5d0;letter-spacing:2px">LAST 72 HOURS • FIELD TRAINING</small><h2>HOW TO PLAY</h2><p>You are the Emergency Operations Commander. Move through Surya Nagar, follow the mission waypoint, interact with emergencies and make decisions that change the city.</p><div class="l72-keys"><div><b>W A S D</b><span>Move</span></div><div><b>E</b><span>Interact / rescue</span></div><div><b>V</b><span>Enter / exit vehicle</span></div><div><b>1–5</b><span>Commands</span></div><div><b>M</b><span>Tactical map</span></div><div><b>ESC</b><span>Pause</span></div></div><p><b style="color:#9fffe5">First objective:</b> reach Coastal Ward, find the glowing marker, then press <b style="color:#ffc857">E</b>.</p><button class="l72-go">START TUTORIAL →</button><p style="text-align:center;font-size:9px">Press ? anytime to reopen this guide.</p></div>';document.body.appendChild(t);
var tr=document.createElement("div");tr.className="l72-tr";document.body.appendChild(tr);var nv=document.createElement("div");nv.className="l72-nav";document.body.appendChild(nv);var tip=document.createElement("div");tip.className="l72-tip";document.body.appendChild(tip);
function cur(){var e=document.getElementById("missionTitle"),q=(e&&e.textContent||"FIRST WARNING").toUpperCase();for(var i=0;i<missions.length;i++)if(q.indexOf(missions[i].t)>=0)return [missions[i],i];return [missions[0],0]}
function draw(){var c=cur(),m=c[0],i=c[1],ar={"NORTH":"↑","SOUTH":"↓","EAST":"→","WEST":"←","NORTH-EAST":"↗","NORTH-WEST":"↖","SOUTH-EAST":"↘","SOUTH-WEST":"↙"};tr.innerHTML="<small>ACTIVE MISSION • "+(i+1)+"/5</small><h3>"+m.t+"</h3><p>"+m.x+"</p><p>📍 <b>"+m.z+"</b></p><p class=\"l72-w\">➤ WAYPOINT: "+m.d+" &nbsp; • &nbsp; INTERACT: E</p>";nv.innerHTML='<div class="ar">'+(ar[m.d]||"◆")+'</div><strong>'+m.z+'</strong><span>FOLLOW WAYPOINT • REACH MARKER</span><div class="l72-list">'+missions.map(function(x,j){return '<div class="'+(j<i?"done":j===i?"on":"")+'">'+(j+1)+". "+x.t+"</div>"}).join("")+"</div>";tip.innerHTML="<b>TIP:</b> "+(i===0?"Press V near the RESCUE SUV, then drive toward the waypoint.":"Reach "+m.z+", then press E to interact.")}
t.querySelector(".l72-go").onclick=function(){t.classList.add("h");draw()};addEventListener("keydown",function(e){if(e.key==="?"||e.key==="/"){t.classList.toggle("h");if(t.classList.contains("h"))draw();e.preventDefault()}if(t.classList.contains("h")&&("e12345m".indexOf(e.key.toLowerCase())>=0))setTimeout(draw,300)});setInterval(function(){if(t.classList.contains("h"))draw()},1000);
})();